<?php
$labels = array();
$labels['gravatar_plugin'] = 'Gravatar Address Book';
$labels['gravatar_use'] = 'Usar Gravatar';
$labels['gravatar_size'] = 'Avatar tamanho (px)';
$labels['gravatar_rating'] = 'Avatar avaliação';
$labels['gravatar_G'] = 'G ';
$labels['gravatar_PG'] = 'PG ';
$labels['gravatar_R'] = 'R ';
$labels['gravatar_X'] = 'X ';
$labels['gravatar_use_custom'] = 'Usar API definida (sempre tem preferência)';
